config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'index', to: 'home#index'
  get 'eat_cookies', to: 'home#eat_cookies'
  get 'discard_cookies', to: 'home#discard_cookies'
  get 'direct_image_link', to: 'home#direct_image_link'

  get 'trial_a', to: 'home#trial_a'
  get 'trial_b', to: 'home#trial_b'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'open-uri'

class HomeController < ApplicationController
  before_action :set_common_instance_variables
  before_action :check_or_create_cloudfront_private_key

  def direct_image_link
    cookies_str = cookies.map { |x| x.join('=') }.join('; ')

    send_file(
      OpenURI.open_uri('https://assets.neo-kobe-city.com/min_yuyake3.jpg', { 'Cookie' => cookies_str }),
      filename: 'min_yuyake3.jpg'
    )
  end

  def index; end

  def trial_a
    eat_cookies(domain: '.neo-kobe-city.com')
  end

  def eat_cookies(domain: request.host, same_site: 'Lax')
    check_or_create_cloudfront_private_key

    cookie_domain = params[:cookie_domain] || domain
    _cookie_same_site = params[:cookie_same_site] || same_site

    signer = Aws::CloudFront::CookieSigner.new(
      key_pair_id: ENV.fetch('CLOUDFRONT_PUBLIC_KEY'),
      private_key_path: Rails.root.join('config/cloudfront_private_key.pem').to_s
    )

    policy_statement = {
      'Statement' => [
        {
          'Resource' => 'http*://assets.neo-kobe-city.com/*',
          'Condition' => {
            DateLessThan: {
              'AWS:EpochTime' => 1.minute.since.to_i
            }
          }
          # "IpAddress" => {
          #   "AWS:SourceIp" => "#{request.remote_ip}/32"
          # }
        },
      ]
    }

    cookie_params = signer.signed_cookie(
      'https://assets.neo-kobe-city.com',
      policy: policy_statement.to_json
    )

    cookie_params.each do |k, v|
      cookies[k] = { value: v, domain: cookie_domain, secure: true }
    end
  end

  # https://koseki.hatenablog.com/entry/20070109/cookiedelete
  # https://stackoverflow.com/questions/6104090/deleting-cookies-from-a-controller
  def discard_cookies
    domains = [
      '.foo.neo-kobe-city.com',
      'foo.neo-kobe-city.com',
      '.neo-kobe-city.com',
      'neo-kobe-city.com',
      '.www.neo-kobe-city.com',
      'www.neo-kobe-city.com',
    ]

    # これでも消えない時がある
    domains.each do |domain|
      cookies.each do |k, _v|
        cookies[k.to_sym] = { value: '', domain: domain, path: '/', expires: Time.zone.at(0) }
        cookies.delete(k)
        cookies.delete(k, domain: domain, path: '/')
      end
    end
  end

  private

  def check_or_create_cloudfront_private_key
    private_key_path = Rails.root.join('config/cloudfront_private_key.pem')

    return if File.exist?(private_key_path)

    File.write(private_key_path, ENV.fetch('CLOUDFRONT_PRIVATE_KEY'))
  end

  def set_common_instance_variables
    @cookies = cookies.to_h
    @request_host = request.host

    @min_tobus2_url = 'https://assets.neo-kobe-city.com/min_tobus2.jpg'
    @min_tukimi3_url = 'https://assets.neo-kobe-city.com/min_tukimi3.jpg'
    @min_undokai1_url = 'https://assets.neo-kobe-city.com/min_undokai1.jpg'
    @min_up1_url = 'https://assets.neo-kobe-city.com/min_up1.jpg'
    @min_xmas3_url = 'https://assets.neo-kobe-city.com/min_xmas3.jpg'
    @min_yuyake3_url = 'https://assets.neo-kobe-city.com/min_yuyake3.jpg'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/discard_cookies.html.erb
<h1>クッキーを捨てました</h1>
<%= link_to 'index に戻る', index_path %>

app/views/home/eat_cookies.html.erb
<h1>1分間有効なクッキーを食べました</h1>
<%= link_to 'index に戻る', index_path %>

app/views/home/index.html.erb
<h2>■<%= link_to "1分間有効なクッキーを食べる (domain: .www.neo-kobe-city.com)", eat_cookies_path %></h2>
<h2>■<%= link_to "1分間有効なクッキーを食べる (domain: .neo-kobe-city.com)", eat_cookies_path(cookie_domain: '.neo-kobe-city.com') %></h2>
<h2>■<%= link_to "クッキーを捨てる（たまにうまくいかないので自分で捨てる方がいい）", discard_cookies_path %></h2>

<hr>

<%= image_tag @min_tobus2_url, height: 400 %>
<p><%= @min_tobus2_url %></p>
<p><%= link_to 'Cookies 付き 直接ダウンロードリンク', direct_image_link_path %></p>

<hr>

<%= image_tag @min_xmas3_url, height: 400 %>
<p><%= @min_xmas3_url %></p>

<%= render 'shared/basic_info' %>

app/views/home/trial_a.html.erb
<h1>trial_a</h1>

<%= image_tag @min_tobus2_url, height: 400 %>
<p><%= @min_tobus2_url %></p>
<p><%= link_to 'Cookies 付き 直接ダウンロードリンク', direct_image_link_path %></p>

<hr>

<%= image_tag @min_xmas3_url, height: 400 %>
<p><%= @min_xmas3_url %></p>

<%= render 'shared/basic_info' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreePlayground</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag('favicon.png') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>

  <script>
    const currentCookies = document.cookie;

    console.log('document.coookie による Cookies の一覧（HttpOnly属性 が付与されているものは含まれない）')
    console.log(currentCookies);
  </script>
  </body>
</html>

app/views/shared/_basic_info.html.erb
<hr>

<h1>Cookies の一覧</h1>

<table border="1">
  <tr>
    <th>名前</th>
    <th>値</th>
  </tr>
  <% @cookies.each do |k ,v| %>
    <tr>
      <td><%= k %></td>
      <td><%= v %></td>
    </tr>
  <% end %>
</table>

<br>
<hr>

<h1>request.host</h1>
<h4><%= @request_host %></h4>